{% set name = "imaris-ims-file-reader" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imaris_ims_file_reader-{{ version }}.tar.gz
  sha256: ae057e49bee6b76cd973bb5dd6882b4dc2ad4d603cf0602acad6c507c23d16ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - h5py >=3.5.0
    - numpy
    - python >=3.7
    - scikit-image

test:
  imports:
    - imaris_ims_file_reader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CBI-PITT/imaris_ims_file_reader
  summary: Class for reading Bitplane imaris files (*.ims)
  license: BSD-3-Clause
  license_file: LICENCE

extra:
  recipe-maintainers:
    - goanpeca
